name: Auto Release Pachage

on:
  push:

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: index charts
        run: |
          ./index.sh
